### PR TITLE
feat(sol-macro): support namespaces

### PR DESCRIPTION
**Pull request by DaniPopes**
Closes https://github.com/alloy-rs/core/issues/660
Closes https://github.com/alloy-rs/core/issues/599

### CODE REVIEW

**Comment by klkvr** [comment]
just tested locally and it seems that derives aren't applied to generated libraries in json abi input causing compilation issues

e.g. this would cause `Lib::Struct doesn't implement Debug`
```rust
sol!(
    #[derive(Debug)]
    Contract,
    r#"[
        {
            "type": "function",
            "name": "f",
            "inputs": [
                {
                    "name": "s",
                    "type": "tuple",
                    "internalType": "struct Lib.Struct",
                    "components": [
                        {
                            "name": "a",
                            "type": "uint256",
                            "internalType": "uint256"
                        }
                    ]
                }
            ],
            "outputs": [],
            "stateMutability": "nonpayable"
        }
    ]"#
);
```

**Comment by DaniPopes** [comment]
And would also be a pretty big breaking change

**Comment by DaniPopes** [comment]
This is broken now, marking as draft again:
```sol
sol! {
    contract Vm {
        struct Wallet {
            uint stuff;
        }

        /// Gets the nonce of an account.
        function getNonce(address account) external view returns (uint64 nonce);

        /// Get the nonce of a `Wallet`.
        function getNonce(Wallet calldata wallet) external returns (uint64 nonce);
    }
}
```

**Comment by klkvr** [comment]
Updated in 18c2ed4, we didn't apply namespaces when resolving overloads

**Pull request merged**
