### PR TITLE
feat: expose Signature<T>

### PR DESCRIPTION
**Pull request by leruaa**
## Motivation

Needed for https://github.com/alloy-rs/alloy/issues/1077 and https://github.com/paradigmxyz/reth/pull/9593

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

### CODE REVIEW

**Comment by leruaa** [comment]
While attempting to apply this refactoring to alloy itself, I start to understand why the `k256` feature is not additive. That to avoid to impl traits like SignableTransaction for multiple Signature types leading to the "multiple `impl`s ... found" error.

I'm trying to find a workaround.

**Comment by mattsse** [comment]
@leruaa perhaps we can introduce a helper trait in alloy for the required rsv function and just that for the alloy encode signature fns instead?

**Review by mattsse — COMMENTED** [review]
this would introduce a ton of friction

I agree the memoized type is a bit horribly, but we can probably solve our problems alloy internally by introducing a signature encodeable trait there so we can implement it for reth's signature type as well. 
can deal with the generic signature snafu later

**Comment by mattsse** [comment]
but perhaps we should consider removing the generic entirely, I find this very useless because this is effectively just duplicating the rsv again

https://github.com/alloy-rs/core/blob/adcf7adfa1f35c56e6331bab85b8c56d32a465f1/crates/primitives/src/signature/sig.rs#L301-L305

**Comment by leruaa** [comment]
@mattsse fyi and for posterity, the branch in alloy applying this refactoring in alloy-core: https://github.com/alloy-rs/alloy/compare/main...leruaa:alloy:signature_refactoring

**Pull request closed without merging**
