### PR TITLE
Derive Serialize/Deserialize if possible

### PR DESCRIPTION
**Pull request by wtdcode**
## Motivation

Derive `Serialize/Deserialize` if possible (with `serde` dep).

## Solution

See diff.

## PR Checklist

- [ x ] Added Tests 
Not needed
- [ x ] Added Documentation
Not needed
- [ x ] Breaking changes
No

### CODE REVIEW

**Comment by prestwich** [comment]
We do not intend these values to be (de)serialized, as they do not correspond to any standard data forma. We aren't really interested in pushing a new standard. For now, all of these types should be in-memory only

Closing as not planned

**Comment by wtdcode** [comment]
> We do not intend these values to be (de)serialized, as they do not correspond to any standard data forma. We aren't really interested in pushing a new standard. For now, all of these types should be in-memory only
> 
> Closing as not planned

I can't understand. It's mostly harmless.

**Comment by wtdcode** [comment]
https://github.com/rust-ethereum/ethabi/blob/b1710adc18f5b771d2d2519c87248b1ba9430778/ethabi/src/token/token.rs#L21

Note `ethabi` also has these. If `alloy` is intended as an alternative to `ethers-rs`, it should also enable these derives, no?

**Comment by wtdcode** [comment]
For tracking pupose, https://serde.rs/remote-derive.html also doesn't work:

```
error[E0277]: the trait bound `DynSolValue: Deserialize<'_>` is not satisfied
    --> -:34:15
     |
34   |     pub args: Vec<DynSolValue>
     |               ^^^^^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `DynSolValue`, which is required by `Vec<DynSolValue>: Deserialize<'_>`
     |
     = help: the following other types implement trait `Deserialize<'de>`:
               <bool as Deserialize<'de>>
               <char as Deserialize<'de>>
               <isize as Deserialize<'de>>
               <i8 as Deserialize<'de>>
               <i16 as Deserialize<'de>>
               <i32 as Deserialize<'de>>
               <i64 as Deserialize<'de>>
               <i128 as Deserialize<'de>>
             and 491 others
     = note: required for `Vec<DynSolValue>` to implement `Deserialize<'_>`
```

**Pull request closed without merging**
