### PR TITLE
fix: properly account for sign in pg to/from sql implementation for signed

### PR DESCRIPTION
**Pull request by luzzif**
## Motivation

The `FromSql`/`ToSql` implementations for the Signed type didn't properly account for signs when dealing with the `NUMERIC` type. This PR addresses it. Check out the screenshot below for an example.

image

### CODE REVIEW

**Review by DaniPopes — APPROVED** [review]
Thanks!

**Comment by luzzif** [comment]
Any idea when we could see this integrated in the `alloy` Rust crate? Or alternatively, could you tell me how I can locally use this?

**Comment by DaniPopes** [comment]
You can patch `alloy-primitives` in your workspace manifest: <https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html>

**Comment by DaniPopes** [comment]
This is now released in [`0.8.8`](https://github.com/alloy-rs/core/releases/tag/v0.8.8).

**Pull request merged**
