### PR TITLE
feat(dyn-abi): derive Default for TypedData

### PR DESCRIPTION
**Pull request by DaniPopes**
cc @prestwich is this right or does this need a custom impl to handle resolver/..?

### CODE REVIEW

**Review by prestwich — CHANGES_REQUESTED** [review]
i think its never correct to have an empty primary type or an empty value. those would both be invalid instances

**Comment by DaniPopes** [comment]
What's a sensible default for no-op / testing then?

**Review by mattsse — COMMENTED** [review]
I think it'd be okay if default is always invalid

**Comment by prestwich** [comment]
> I think it'd be okay if default is always invalid

I would be very against this

why not just add a `cfg_attr(test, derive(Default))`

**Comment by mattsse** [comment]
this only works internally I think

**Comment by prestwich** [comment]
instead of proposing a feature, can you talk about the need? what are you trying to test?

**Comment by DaniPopes** [comment]
dummy input to eth_signTypedData

**Comment by prestwich** [comment]
sure but do you want input that's going to cause an error, GIGO, or something else?

**Comment by gakonst** [comment]
if useful for testing we have used `test-utils` features in the past instead of `cfg_attr(test)`, and i'd be ok w it

**Pull request closed without merging**
