### PR TITLE
chore: rename coding functions

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation

More intuitive

## Solution

- `{encode,decode}` -> `{encode,decode}_sequence`
- `{encode,decode}_single` -> `{encode,decode}`

## PR Checklist

- [x] Added Tests
- [x] Added Documentation
- [x] Breaking changes

### CODE REVIEW

**Review by gakonst — DISMISSED** [review]
ok w me pending conflicts

**Comment by prestwich** [comment]
dont merge until we have a migration comms plan

**Review by prestwich — APPROVED** [review]
before tagging a release we should write a telegram announcement cc @gakonst

**Comment by gakonst** [comment]
yup - left a note about it in TG, and we'll re-announce

**Pull request merged**
